### ISSUE TITLE
Outer `html` element missing from HTML screenshots

### ISSUE THREAD

**Issue by johnbillion** [forceedge01/behat-fail-aid#11]
Thank you for creating and maintaining this extension, it's a *huge* aid for debugging failing tests. 🍻 

**What is the issue?**

When an HTML screenshot gets saved, the outer `<html>` element is not present in the source code.

I'm not familiar enough with the internals of Mink etc to know whether this is an issue with Fail Aid, or a lower level issue.

**How did it happen?**

One of my features tests the value of the `lang` attribute on the `html` element to ensure the page language is as expected. The HTML saved by Fail Aid after a failed scenario does not include the outer `html` element.

**What should have happened?**

Ideally the complete page source gets saved.

**Comment by forceedge01** [comment]
Thanks @johnbillion for reporting this issue, I will review your PR and get this merged ASAP.
